#!/bin/bash

# VQA Training with OOP Architecture - Example Commands

echo "=========================================="
echo "VQA Training Examples - OOP Architecture"
echo "=========================================="
echo ""

echo "1. Basic Training (No Augmentation)"
echo "-----------------------------------"
echo "python train.py \\"
echo "    --dataset_name vivqa \\"
echo "    --epochs 30 \\"
echo "    --batch_size 64 \\"
echo "    --learning_rate 1e-4"
echo ""

echo "2. Training with Masked Augmentation (Easy)"
echo "--------------------------------------------"
echo "python train.py \\"
echo "    --dataset_name vivqa \\"
echo "    --enable_augmentation \\"
echo "    --augmentation_type masked \\"
echo "    --patch_size 16 \\"
echo "    --epochs 30 \\"
echo "    --batch_size 64"
echo ""

echo "3. Training with Curriculum Learning"
echo "------------------------------------"
echo "python train.py \\"
echo "    --dataset_name openvivqa \\"
echo "    --enable_augmentation \\"
echo "    --enable_curriculum \\"
echo "    --augmentation_type masked \\"
echo "    --epochs 50 \\"
echo "    --easy_epochs 15 \\"
echo "    --medium_epochs 15 \\"
echo "    --hard_epochs 20 \\"
echo "    --batch_size 32 \\"
echo "    --learning_rate 5e-5"
echo ""

echo "4. Full Configuration with WandB Logging"
echo "----------------------------------------"
echo "python train.py \\"
echo "    --dataset_name vitextvqa \\"
echo "    --vis_model_name google/vit-base-patch16-224 \\"
echo "    --text_model_name vinai/bartpho-syllable-base \\"
echo "    --enable_augmentation \\"
echo "    --enable_curriculum \\"
echo "    --augmentation_type masked \\"
echo "    --patch_size 16 \\"
echo "    --epochs 50 \\"
echo "    --easy_epochs 15 \\"
echo "    --medium_epochs 15 \\"
echo "    --hard_epochs 20 \\"
echo "    --batch_size 32 \\"
echo "    --seq_len 64 \\"
echo "    --learning_rate 5e-5 \\"
echo "    --weight_decay 1e-4 \\"
echo "    --gradient_accumulation 2 \\"
echo "    --warmup_steps 500 \\"
echo "    --fp16 \\"
echo "    --patience 5 \\"
echo "    --logging_steps 100 \\"
echo "    --report_to_wandb \\"
echo "    --wandb_name VQA-Curriculum-Experiments \\"
echo "    --run_name curriculum-masked-v1 \\"
echo "    --output_dir runs/curriculum"
echo ""

echo "5. Multi-Dataset Experiment with Curriculum"
echo "-------------------------------------------"
echo "# Train on different datasets with same curriculum setup"
echo ""
for dataset in vivqa openvivqa vitextvqa; do
    echo "python train.py \\"
    echo "    --dataset_name $dataset \\"
    echo "    --enable_augmentation \\"
    echo "    --enable_curriculum \\"
    echo "    --epochs 30 \\"
    echo "    --easy_epochs 9 \\"
    echo "    --medium_epochs 9 \\"
    echo "    --hard_epochs 12 \\"
    echo "    --report_to_wandb \\"
    echo "    --run_name curriculum-$dataset"
    echo ""
done

echo "6. Ablation Study: With vs Without Curriculum"
echo "---------------------------------------------"
echo "# Without curriculum (baseline)"
echo "python train.py \\"
echo "    --dataset_name vivqa \\"
echo "    --enable_augmentation \\"
echo "    --augmentation_type masked \\"
echo "    --epochs 30 \\"
echo "    --run_name baseline-no-curriculum"
echo ""
echo "# With curriculum"
echo "python train.py \\"
echo "    --dataset_name vivqa \\"
echo "    --enable_augmentation \\"
echo "    --enable_curriculum \\"
echo "    --epochs 30 \\"
echo "    --easy_epochs 9 \\"
echo "    --medium_epochs 9 \\"
echo "    --hard_epochs 12 \\"
echo "    --run_name curriculum-enabled"
echo ""

echo "7. Quick Test Run (5 epochs)"
echo "----------------------------"
echo "python train.py \\"
echo "    --dataset_name vivqa \\"
echo "    --enable_augmentation \\"
echo "    --enable_curriculum \\"
echo "    --epochs 5 \\"
echo "    --easy_epochs 2 \\"
echo "    --medium_epochs 2 \\"
echo "    --hard_epochs 1 \\"
echo "    --batch_size 16 \\"
echo "    --logging_steps 10"
echo ""

echo "=========================================="
echo "Notes:"
echo "=========================================="
echo "- Make sure to install dependencies: pip install -r requirements.txt"
echo "- For WandB logging, set WANDB_API_KEY environment variable"
echo "- Adjust batch_size based on your GPU memory"
echo "- Use --fp16 for mixed precision training on compatible GPUs"
echo "- Results will be saved in the output_dir (default: runs/)"
echo ""
